config/routes.rb
Jap::Application.routes.draw do
  resources :musics
  namespace :api do
    resources :musics
  end
  root :to => 'musics#index'
end

app/models/api_key.rb
class ApiKey < ActiveRecord::Base
  attr_accessible :access_token

  before_create :generate_access_token

  private
    def generate_access_token
      begin
        self.access_token = SecureRandom.hex
      end
    end
end

app/models/music.rb
class Music < ActiveRecord::Base
  attr_accessible :artist, :name, :year
end

app/controllers/api/musics_controller.rb
class Api::MusicsController < ApplicationController
  before_filter :restrict_access

  def index
    @music = Music.all
    respond_to do |format|
      format.json { render :json => @music }
    end
  end

  private
    def restrict_access
      authenticate_or_request_with_http_token do |token, options|
        ApiKey.exists?(access_token: token)
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @musics }
    end
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @music = Music.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/new
  # GET /musics/new.json
  def new
    @music = Music.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/1/edit
  def edit
    @music = Music.find(params[:id])
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = Music.new(params[:music])

    respond_to do |format|
      if @music.save
        format.html { redirect_to @music, notice: 'Music was successfully created.' }
        format.json { render json: @music, status: :created, location: @music }
      else
        format.html { render action: "new" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /musics/1
  # PUT /musics/1.json
  def update
    @music = Music.find(params[:id])

    respond_to do |format|
      if @music.update_attributes(params[:music])
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music = Music.find(params[:id])
    @music.destroy

    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jap</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :artist %><br />
    <%= f.text_field :artist %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Artist</th>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @musics.each do |music| %>
  <tr>
    <td><%= music.name %></td>
    <td><%= music.artist %></td>
    <td><%= music.year %></td>
    <td><%= link_to 'Show', music %></td>
    <td><%= link_to 'Edit', edit_music_path(music) %></td>
    <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %>

app/views/musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @music.name %>
</p>

<p>
  <b>Artist:</b>
  <%= @music.artist %>
</p>

<p>
  <b>Year:</b>
  <%= @music.year %>
</p>


<%= link_to 'Edit', edit_music_path(@music) %> |
<%= link_to 'Back', musics_path %>